# Generated by Django 4.1 on 2022-08-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangularOperations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticleModel',
        ),
    ]
